export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const TOKEN_USER_REQUEST = "TOKEN_USER_REQUEST";
export const TOKEN_USER_SUCCESS = "TOKEN_USER_SUCCESS";
export const TOKEN_USER_FAILED = "TOKEN_USER_FAILED";

export const LOG_OUT = "LOG_OUT";

export const USER_PROFILE_UPDATE = "USER_PROFILE_UPDATE";
export const FEATURED_COLLECTION_SLIDER = "FEATURED_COLLECTION_SLIDER";
export const PROFILE_PHOTO_UPLOAD = "PROFILE_PHOTO_UPLOAD";
export const COVER_PHOTO_UPLOAD = "COVER_PHOTO_UPLOAD";

export const GET_ALL_USER = "GET_ALL_USER";
export const ADD_FRIEND = "ADD_FRIEND";
